name: ✨ Feature Request
description: Suggest a new feature or enhancement for OpenUSPolitics.org
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this feature affect?
      options:
        - Website/Frontend (Next.js)
        - ETL Pipeline (Python)
        - Bill Analysis (Claude AI)
        - Data Storage
        - GitHub Actions/CI
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for usability
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: |
        As a [user type], I want to [action] so that [benefit]
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other sites
      placeholder: Paste images or links here
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details (Optional)
      description: If you have ideas about how this could be implemented, share them here
      placeholder: Technical implementation suggestions
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with OpenUSPolitics.org's mission of non-partisan political information
          required: true
        - label: I am willing to help implement this feature if needed
          required: false
